logo: # add logo name
title: Lyric Haven
description: > # this means to ignore newlines until "baseurl:"
  A collection of song lyrics, reviews, LRC files, and the like.
permalink: ':title/'
baseurl: "/Lyric_Haven" # the subpath of your site, e.g. /blog
url: "https://aspiring-writer.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: # add banner title
banner-desc: # add banner description

# Author settings
author-pic: face.jpg # your photo
author-name: Bravisha Skietano # your name
about-author: Born-again believer, aspiring writer, future web developer. # about author
email: yaolson01@gmail.com # your email
phone: # your pnone number
website: https://aspiring-writer.github.io # you website

# Social link
google_url:    # add url link
twitter_url:   # add url link
instagram_url: # add url link
pinterest_url: # add url link
dribbble_url:  # add url link
facebook_url:  # add url link

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap

gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
